# Schema for the configuration files of the Resource Hub Default theme.
resourcehub_theme.settings:
  type: theme_settings
  label: 'Resource Hub Default settings'
  mapping:
    font_size:
      type: integer
      label: Font size
