# Schema for the configuration files of the Resource Hub Default theme.
resourcehub_theme.settings:
  type: theme_settings
  label: 'Resource Hub Default settings'
  mapping:
    features:
      type: mapping
      mapping:
        branding_logo:
          type: boolean
          label: Display branding logo
        branding_name:
          type: boolean
          label: Display branding name
